# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Pacific Northwest National Laboratory'
    description: 'A highly-customizable Hugo résumé theme powered by Hugo Blox Builder.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: 'G-8ZTWWKQ9R5'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
#header:
#  navbar:
#    enable: true
#    blox: floating-theme-toggler

header:
  navbar:
    enable: true
    blox: "navbar"
    align: c
    fixed_to_top: true
    logo:
      # Logo text
      text: "Shady E. Ahmed"
      # Logo filename in `assets/media/` folder
      filename: "assets/media/icon.png"
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true
    
# Site footer
footer:
  copyright:
    notice: '© {year} Shady Ahmed. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true
